CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    city TEXT,
    venue TEXT,
    batting_team TEXT NOT NULL,
    over_number INTEGER NOT NULL,
    batter TEXT NOT NULL,
    bowler TEXT NOT NULL,
    runs_batter INTEGER NOT NULL DEFAULT 0,
    runs_total INTEGER NOT NULL DEFAULT 0,
    runs_extras INTEGER NOT NULL DEFAULT 0,
    is_boundary BOOLEAN NOT NULL DEFAULT FALSE,
    is_dot_ball BOOLEAN NOT NULL DEFAULT FALSE,
    player_out TEXT,
    bowler_for_wicket TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);