-- base table
CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    city TEXT,
    venue TEXT,
    batting_team TEXT NOT NULL,
    over_number INTEGER NOT NULL,
    batter TEXT NOT NULL,
    bowler TEXT NOT NULL,
    runs_batter INTEGER NOT NULL DEFAULT 0,
    runs_total INTEGER NOT NULL DEFAULT 0,
    runs_extras INTEGER NOT NULL DEFAULT 0,
    is_boundary BOOLEAN NOT NULL DEFAULT FALSE,
    is_dot_ball BOOLEAN NOT NULL DEFAULT FALSE,
    player_out TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- indexes to speed queries on base table
CREATE INDEX idx_deliveries_match_id ON deliveries(match_id);
CREATE INDEX idx_deliveries_batter ON deliveries(batter);
CREATE INDEX idx_deliveries_bowler ON deliveries(bowler);
CREATE INDEX idx_deliveries_team ON deliveries(batting_team);

-- derived tables

CREATE TABLE match_stats (
    match_id TEXT PRIMARY KEY,
    match_date DATE NOT NULL,
    city TEXT,
    venue TEXT,
    team_1 TEXT NOT NULL,
    team_2 TEXT NOT NULL,
    team_1_score INTEGER,
    team_2_score INTEGER,
    team_1_wickets INTEGER,
    team_2_wickets INTEGER,
    winner TEXT,
    margin_runs INTEGER,
    margin_wickets INTEGER,
    total_boundaries INTEGER,
    total_sixes INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_match_stats_date ON match_stats(match_date);
CREATE INDEX idx_match_stats_venue ON match_stats(venue);

CREATE TABLE batter_stats (
    batter TEXT PRIMARY KEY,
    matches_played INTEGER NOT NULL DEFAULT 0,
    innings INTEGER NOT NULL DEFAULT 0,
    total_runs INTEGER NOT NULL DEFAULT 0,
    balls_faced INTEGER NOT NULL DEFAULT 0,
    times_out INTEGER NOT NULL DEFAULT 0,
    batting_average DECIMAL(6,2),
    strike_rate DECIMAL(6,2),
    highest_score INTEGER,
    total_fours INTEGER NOT NULL DEFAULT 0,
    total_sixes INTEGER NOT NULL DEFAULT 0,
    fifties INTEGER NOT NULL DEFAULT 0,
    hundreds INTEGER NOT NULL DEFAULT 0,
    dot_ball_percentage DECIMAL(5,2),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_batter_stats_runs ON batter_stats(total_runs DESC);
CREATE INDEX idx_batter_stats_average ON batter_stats(batting_average DESC);

CREATE TABLE bowler_stats (
    bowler TEXT PRIMARY KEY,
    matches_played INTEGER NOT NULL DEFAULT 0,
    innings_bowled INTEGER NOT NULL DEFAULT 0,
    overs_bowled DECIMAL(6,1),
    balls_bowled INTEGER NOT NULL DEFAULT 0,
    runs_conceded INTEGER NOT NULL DEFAULT 0,
    wickets_taken INTEGER NOT NULL DEFAULT 0,
    bowling_average DECIMAL(6,2),
    economy_rate DECIMAL(5,2),
    strike_rate DECIMAL(6,2),
    best_figures TEXT,
    dot_balls INTEGER NOT NULL DEFAULT 0,
    extras_conceded INTEGER NOT NULL DEFAULT 0,
    four_wickets INTEGER NOT NULL DEFAULT 0,
    five_wickets INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_bowler_stats_wickets ON bowler_stats(wickets_taken DESC);
CREATE INDEX idx_bowler_stats_economy ON bowler_stats(economy_rate ASC);